#!/usr/bin/env python3

import click

from ros_introspection.cmake import Command, CommandGroup
from ros_introspection.util import get_packages


def convert_whitespace(s):
    ns = ''
    for c in s:
        if c == ' ':
            ns += '.'
        elif c == '\t':
            ns += '→\t'
        elif c == '\n':
            ns += '↵\n'
        else:
            ns += c
    return ns


def pretty_command_print(cmd):
    click.secho(cmd.command_name + convert_whitespace(cmd.pre_paren) + '(', fg='white', nl=False)
    for section in cmd.sections:
        click.secho(convert_whitespace(section.style.prename) + section.name, fg='green', nl=False)
        if len(section.name) > 0:
            if len(section.values) > 0 or '\n' in section.style.name_val_sep:
                click.secho(convert_whitespace(section.style.name_val_sep), fg='red')
        click.secho(section.style.val_sep.join(section.values), fg='yellow', nl=False)
    click.secho(')', fg='white', nl=False)


def pretty_cmake_print(cmake):
    for i, content in enumerate(cmake.contents):
        if content.__class__ == Command:
            pretty_command_print(content)
        elif content.__class__ == CommandGroup:
            pretty_command_print(content.initial_tag)
            pretty_cmake_print(content.sub)
            pretty_command_print(content.close_tag)
        else:
            click.secho('[', fg='cyan', nl=False)
            click.secho(convert_whitespace(content), fg='blue', nl=False)
            click.secho(']', fg='cyan', nl=False)


for package in get_packages():
    pretty_cmake_print(package.cmake)
